-- -- -- Users Table
-- -- CREATE TABLE "Users" (
-- --     "id" SERIAL PRIMARY KEY,
-- --     "name" VARCHAR(100) NOT NULL,
-- --     "email" VARCHAR(100) UNIQUE NOT NULL,
-- --     "password" VARCHAR(255) NOT NULL,
-- --     "role" VARCHAR(20) DEFAULT 'user' CHECK ("role" IN ('user', 'admin')),
-- --     "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--         "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
-- -- );

-- -- -- Joke table
-- -- CREATE TABLE "Jokes" (
-- --     "id" SERIAL PRIMARY KEY,
-- --     "user_id" INT REFERENCES "Users"(id) ON DELETE CASCADE,
-- --     "title" VARCHAR(255) NOT NULL,
-- --     "content" TEXT NOT NULL,
-- --     "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
-- -- );
-- -- Users Table
-- CREATE TABLE "Users" (
--     user_id SERIAL PRIMARY KEY,
--     username VARCHAR(50) NOT NULL,
--     email VARCHAR(100) NOT NULL UNIQUE,
--     password_hash VARCHAR(255) NOT NULL,
--     profile_picture VARCHAR(255),
--     bio TEXT,
--     registration_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     last_login TIMESTAMP WITH TIME ZONE,
--     is_active BOOLEAN DEFAULT TRUE,
--     is_admin BOOLEAN DEFAULT FALSE
-- );

-- -- Jokes Table
-- CREATE TABLE "Jokes" (
--     joke_id SERIAL PRIMARY KEY,
--     user_id INTEGER NOT NULL,
--     title VARCHAR(255) NOT NULL,
--     content TEXT NOT NULL,
--     category VARCHAR(50),
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (user_id) REFERENCES "Users"(user_id) ON DELETE CASCADE
-- );

-- -- Comments Table
-- CREATE TABLE "Comments" (
--     comment_id SERIAL PRIMARY KEY,
--     user_id INTEGER NOT NULL,
--     joke_id INTEGER NOT NULL,
--     content TEXT NOT NULL,
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (user_id) REFERENCES "Users"(user_id) ON DELETE CASCADE,
--     FOREIGN KEY (joke_id) REFERENCES "Jokes"(joke_id) ON DELETE CASCADE
-- );

-- -- Likes Table
-- CREATE TABLE "Likes" (
--     like_id SERIAL PRIMARY KEY,
--     user_id INTEGER NOT NULL,
--     joke_id INTEGER NOT NULL,
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (user_id) REFERENCES "Users"(user_id) ON DELETE CASCADE,
--     FOREIGN KEY (joke_id) REFERENCES "Jokes"(joke_id) ON DELETE CASCADE
-- );
